# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cnysten <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/29 14:40:37 by cnysten           #+#    #+#              #
#    Updated: 2021/10/29 14:47:03 by cnysten          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRCS = ft_display_file.c

all: $(NAME)
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRCS)

clean:

fclean: clean
	/bin/rm/ ft_display_file

re: fclean all

